[2025-05-05T10:14:32.012+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=statsbomb_load_postgres/run_id=manual__2025-05-05T10:14:29.000683+00:00/task_id=upsert_competitions permission to 509
[2025-05-05T10:14:32.077+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=statsbomb_load_postgres/run_id=manual__2025-05-05T10:14:29.000683+00:00/task_id=upsert_competitions permission to 509
[2025-05-05T10:14:32.128+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: statsbomb_load_postgres.upsert_competitions manual__2025-05-05T10:14:29.000683+00:00 [queued]>
[2025-05-05T10:14:32.144+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: statsbomb_load_postgres.upsert_competitions manual__2025-05-05T10:14:29.000683+00:00 [queued]>
[2025-05-05T10:14:32.146+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-05-05T10:14:32.166+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): upsert_competitions> on 2025-05-05 10:14:29.000683+00:00
[2025-05-05T10:14:32.172+0000] {standard_task_runner.py:57} INFO - Started process 720 to run task
[2025-05-05T10:14:32.179+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'statsbomb_load_postgres', 'upsert_competitions', 'manual__2025-05-05T10:14:29.000683+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/load_to_postgres.py', '--cfg-path', '/tmp/tmpl7vsayyr']
[2025-05-05T10:14:32.183+0000] {standard_task_runner.py:85} INFO - Job 58: Subtask upsert_competitions
[2025-05-05T10:14:32.305+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=statsbomb_load_postgres/run_id=manual__2025-05-05T10:14:29.000683+00:00/task_id=upsert_competitions permission to 509
[2025-05-05T10:14:32.331+0000] {task_command.py:415} INFO - Running <TaskInstance: statsbomb_load_postgres.upsert_competitions manual__2025-05-05T10:14:29.000683+00:00 [running]> on host cf8b24399b8b
[2025-05-05T10:14:32.487+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='statsbomb_load_postgres' AIRFLOW_CTX_TASK_ID='upsert_competitions' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T10:14:29.000683+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-05T10:14:29.000683+00:00'
[2025-05-05T10:14:32.494+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-05-05T10:14:32.504+0000] {base.py:73} INFO - Using connection ID 'minio_default' for task execution.
[2025-05-05T10:14:32.515+0000] {logging_mixin.py:151} WARNING - <string>:8 AirflowProviderDeprecationWarning: AWS Connection (conn_id='minio_default', conn_type='s3') has connection type 's3', which has been replaced by connection type 'aws'. Please update your connection to have `conn_type='aws'`.
[2025-05-05T10:14:32.517+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_default', conn_type='s3') credentials retrieved from login and password.
[2025-05-05T10:14:32.521+0000] {logging_mixin.py:151} WARNING - <string>:8 AirflowProviderDeprecationWarning: Host minio specified in the connection is not used. Please, set it on extra['endpoint_url'] instead
[2025-05-05T10:14:41.652+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-05T10:14:41.787+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_to_postgres.py", line 27, in upsert_competitions
    hook_pg.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 154, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres" (172.19.0.5), port 5432 failed: FATAL:  password authentication failed for user "postgres"

[2025-05-05T10:14:41.966+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=statsbomb_load_postgres, task_id=upsert_competitions, execution_date=20250505T101429, start_date=20250505T101432, end_date=20250505T101441
[2025-05-05T10:14:42.128+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 58 for task upsert_competitions (connection to server at "postgres" (172.19.0.5), port 5432 failed: FATAL:  password authentication failed for user "postgres"
; 720)
[2025-05-05T10:14:42.158+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-05T10:14:42.288+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
