[2025-05-05T10:19:49.454+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=statsbomb_load_postgres/run_id=manual__2025-05-05T10:14:29.000683+00:00/task_id=upsert_competitions permission to 509
[2025-05-05T10:19:49.521+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=statsbomb_load_postgres/run_id=manual__2025-05-05T10:14:29.000683+00:00/task_id=upsert_competitions permission to 509
[2025-05-05T10:19:49.562+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: statsbomb_load_postgres.upsert_competitions manual__2025-05-05T10:14:29.000683+00:00 [queued]>
[2025-05-05T10:19:49.574+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: statsbomb_load_postgres.upsert_competitions manual__2025-05-05T10:14:29.000683+00:00 [queued]>
[2025-05-05T10:19:49.575+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-05-05T10:19:49.592+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): upsert_competitions> on 2025-05-05 10:14:29.000683+00:00
[2025-05-05T10:19:49.598+0000] {standard_task_runner.py:57} INFO - Started process 1236 to run task
[2025-05-05T10:19:49.602+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'statsbomb_load_postgres', 'upsert_competitions', 'manual__2025-05-05T10:14:29.000683+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/load_to_postgres.py', '--cfg-path', '/tmp/tmpobzxc11b']
[2025-05-05T10:19:49.605+0000] {standard_task_runner.py:85} INFO - Job 61: Subtask upsert_competitions
[2025-05-05T10:19:49.667+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=statsbomb_load_postgres/run_id=manual__2025-05-05T10:14:29.000683+00:00/task_id=upsert_competitions permission to 509
[2025-05-05T10:19:49.678+0000] {task_command.py:415} INFO - Running <TaskInstance: statsbomb_load_postgres.upsert_competitions manual__2025-05-05T10:14:29.000683+00:00 [running]> on host cf8b24399b8b
[2025-05-05T10:19:49.785+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='statsbomb_load_postgres' AIRFLOW_CTX_TASK_ID='upsert_competitions' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T10:14:29.000683+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-05T10:14:29.000683+00:00'
[2025-05-05T10:19:49.789+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-05-05T10:19:49.791+0000] {base.py:73} INFO - Using connection ID 'minio_default' for task execution.
[2025-05-05T10:19:49.798+0000] {logging_mixin.py:151} WARNING - <string>:8 AirflowProviderDeprecationWarning: AWS Connection (conn_id='minio_default', conn_type='s3') has connection type 's3', which has been replaced by connection type 'aws'. Please update your connection to have `conn_type='aws'`.
[2025-05-05T10:19:49.799+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_default', conn_type='s3') credentials retrieved from login and password.
[2025-05-05T10:19:49.802+0000] {logging_mixin.py:151} WARNING - <string>:8 AirflowProviderDeprecationWarning: Host minio specified in the connection is not used. Please, set it on extra['endpoint_url'] instead
[2025-05-05T10:19:52.103+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-05T10:19:52.496+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_to_postgres.py", line 27, in upsert_competitions
    hook_pg.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 154, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres" (172.19.0.5), port 5432 failed: FATAL:  password authentication failed for user "postgres"

[2025-05-05T10:19:53.475+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=statsbomb_load_postgres, task_id=upsert_competitions, execution_date=20250505T101429, start_date=20250505T101949, end_date=20250505T101953
[2025-05-05T10:19:53.615+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 61 for task upsert_competitions (connection to server at "postgres" (172.19.0.5), port 5432 failed: FATAL:  password authentication failed for user "postgres"
; 1236)
[2025-05-05T10:19:53.764+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-05T10:19:53.882+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
