[2025-05-02T22:01:40.682+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=statsbomb_full_ingestion/run_id=manual__2025-05-02T21:55:24+00:00/task_id=ingest_events_lineups permission to 509
[2025-05-02T22:01:40.728+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=statsbomb_full_ingestion/run_id=manual__2025-05-02T21:55:24+00:00/task_id=ingest_events_lineups permission to 509
[2025-05-02T22:01:40.762+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: statsbomb_full_ingestion.ingest_events_lineups manual__2025-05-02T21:55:24+00:00 [queued]>
[2025-05-02T22:01:40.774+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: statsbomb_full_ingestion.ingest_events_lineups manual__2025-05-02T21:55:24+00:00 [queued]>
[2025-05-02T22:01:40.775+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-05-02T22:01:40.791+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): ingest_events_lineups> on 2025-05-02 21:55:24+00:00
[2025-05-02T22:01:40.797+0000] {standard_task_runner.py:57} INFO - Started process 791 to run task
[2025-05-02T22:01:40.801+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'statsbomb_full_ingestion', 'ingest_events_lineups', 'manual__2025-05-02T21:55:24+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/statsbomb_ingestion.py', '--cfg-path', '/tmp/tmpnbks9a4x']
[2025-05-02T22:01:40.804+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask ingest_events_lineups
[2025-05-02T22:01:40.862+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=statsbomb_full_ingestion/run_id=manual__2025-05-02T21:55:24+00:00/task_id=ingest_events_lineups permission to 509
[2025-05-02T22:01:40.872+0000] {task_command.py:415} INFO - Running <TaskInstance: statsbomb_full_ingestion.ingest_events_lineups manual__2025-05-02T21:55:24+00:00 [running]> on host e2d1066c2b98
[2025-05-02T22:01:40.956+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='statsbomb_full_ingestion' AIRFLOW_CTX_TASK_ID='ingest_events_lineups' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T21:55:24+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-02T21:55:24+00:00'
[2025-05-02T22:01:40.960+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-05-02T22:01:40.963+0000] {base.py:73} INFO - Using connection ID 'minio_default' for task execution.
[2025-05-02T22:01:40.969+0000] {logging_mixin.py:151} WARNING - <string>:8 AirflowProviderDeprecationWarning: AWS Connection (conn_id='minio_default', conn_type='s3') has connection type 's3', which has been replaced by connection type 'aws'. Please update your connection to have `conn_type='aws'`.
[2025-05-02T22:01:40.972+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_default', conn_type='s3') credentials retrieved from login and password.
[2025-05-02T22:01:40.974+0000] {logging_mixin.py:151} WARNING - <string>:8 AirflowProviderDeprecationWarning: Host minio specified in the connection is not used. Please, set it on extra['endpoint_url'] instead
[2025-05-02T22:01:41.720+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/statsbomb_ingestion.py", line 60, in ingest_events_lineups
    fetch_and_upload(f"events/{cid}/{sid}/{mid}.json",
  File "/opt/airflow/dags/statsbomb_ingestion.py", line 25, in fetch_and_upload
    resp.raise_for_status()
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/statsbomb/open-data/master/data/events/9/281/3895302.json
[2025-05-02T22:01:41.747+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=statsbomb_full_ingestion, task_id=ingest_events_lineups, execution_date=20250502T215524, start_date=20250502T220140, end_date=20250502T220141
[2025-05-02T22:01:41.781+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 14 for task ingest_events_lineups (404 Client Error: Not Found for url: https://raw.githubusercontent.com/statsbomb/open-data/master/data/events/9/281/3895302.json; 791)
[2025-05-02T22:01:41.805+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-02T22:01:41.893+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
