[2025-05-02T22:05:44.057+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=statsbomb_full_ingestion/run_id=scheduled__2025-05-01T22:00:00+00:00/task_id=ingest_events_lineups permission to 509
[2025-05-02T22:05:44.094+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=statsbomb_full_ingestion/run_id=scheduled__2025-05-01T22:00:00+00:00/task_id=ingest_events_lineups permission to 509
[2025-05-02T22:05:44.126+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: statsbomb_full_ingestion.ingest_events_lineups scheduled__2025-05-01T22:00:00+00:00 [queued]>
[2025-05-02T22:05:44.137+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: statsbomb_full_ingestion.ingest_events_lineups scheduled__2025-05-01T22:00:00+00:00 [queued]>
[2025-05-02T22:05:44.139+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-05-02T22:05:44.153+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): ingest_events_lineups> on 2025-05-01 22:00:00+00:00
[2025-05-02T22:05:44.158+0000] {standard_task_runner.py:57} INFO - Started process 835 to run task
[2025-05-02T22:05:44.161+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'statsbomb_full_ingestion', 'ingest_events_lineups', 'scheduled__2025-05-01T22:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/statsbomb_ingestion.py', '--cfg-path', '/tmp/tmpe6cm5rrx']
[2025-05-02T22:05:44.165+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask ingest_events_lineups
[2025-05-02T22:05:44.221+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=statsbomb_full_ingestion/run_id=scheduled__2025-05-01T22:00:00+00:00/task_id=ingest_events_lineups permission to 509
[2025-05-02T22:05:44.230+0000] {task_command.py:415} INFO - Running <TaskInstance: statsbomb_full_ingestion.ingest_events_lineups scheduled__2025-05-01T22:00:00+00:00 [running]> on host e2d1066c2b98
[2025-05-02T22:05:44.313+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='statsbomb_full_ingestion' AIRFLOW_CTX_TASK_ID='ingest_events_lineups' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T22:00:00+00:00'
[2025-05-02T22:05:44.316+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-05-02T22:05:44.318+0000] {base.py:73} INFO - Using connection ID 'minio_default' for task execution.
[2025-05-02T22:05:44.324+0000] {logging_mixin.py:151} WARNING - <string>:8 AirflowProviderDeprecationWarning: AWS Connection (conn_id='minio_default', conn_type='s3') has connection type 's3', which has been replaced by connection type 'aws'. Please update your connection to have `conn_type='aws'`.
[2025-05-02T22:05:44.325+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_default', conn_type='s3') credentials retrieved from login and password.
[2025-05-02T22:05:44.327+0000] {logging_mixin.py:151} WARNING - <string>:8 AirflowProviderDeprecationWarning: Host minio specified in the connection is not used. Please, set it on extra['endpoint_url'] instead
[2025-05-02T22:05:44.958+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/statsbomb_ingestion.py", line 60, in ingest_events_lineups
    fetch_and_upload(f"events/{cid}/{sid}/{mid}.json",
  File "/opt/airflow/dags/statsbomb_ingestion.py", line 25, in fetch_and_upload
    resp.raise_for_status()
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/statsbomb/open-data/master/data/events/9/281/3895302.json
[2025-05-02T22:05:44.973+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=statsbomb_full_ingestion, task_id=ingest_events_lineups, execution_date=20250501T220000, start_date=20250502T220544, end_date=20250502T220544
[2025-05-02T22:05:44.988+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 16 for task ingest_events_lineups (404 Client Error: Not Found for url: https://raw.githubusercontent.com/statsbomb/open-data/master/data/events/9/281/3895302.json; 835)
[2025-05-02T22:05:45.036+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-02T22:05:45.079+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
