[2025-05-05T10:58:33.331+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=statsbomb_load_postgres/run_id=manual__2025-05-05T10:57:07.890686+00:00/task_id=load_lineups permission to 509
[2025-05-05T10:58:33.383+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=statsbomb_load_postgres/run_id=manual__2025-05-05T10:57:07.890686+00:00/task_id=load_lineups permission to 509
[2025-05-05T10:58:33.420+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: statsbomb_load_postgres.load_lineups manual__2025-05-05T10:57:07.890686+00:00 [queued]>
[2025-05-05T10:58:33.432+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: statsbomb_load_postgres.load_lineups manual__2025-05-05T10:57:07.890686+00:00 [queued]>
[2025-05-05T10:58:33.433+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-05-05T10:58:33.456+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): load_lineups> on 2025-05-05 10:57:07.890686+00:00
[2025-05-05T10:58:33.464+0000] {standard_task_runner.py:57} INFO - Started process 267 to run task
[2025-05-05T10:58:33.467+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'statsbomb_load_postgres', 'load_lineups', 'manual__2025-05-05T10:57:07.890686+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/load_to_postgres.py', '--cfg-path', '/tmp/tmp94cf1mqt']
[2025-05-05T10:58:33.470+0000] {standard_task_runner.py:85} INFO - Job 85: Subtask load_lineups
[2025-05-05T10:58:33.531+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=statsbomb_load_postgres/run_id=manual__2025-05-05T10:57:07.890686+00:00/task_id=load_lineups permission to 509
[2025-05-05T10:58:33.543+0000] {task_command.py:415} INFO - Running <TaskInstance: statsbomb_load_postgres.load_lineups manual__2025-05-05T10:57:07.890686+00:00 [running]> on host 53d7affc39e7
[2025-05-05T10:58:33.629+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='statsbomb_load_postgres' AIRFLOW_CTX_TASK_ID='load_lineups' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T10:57:07.890686+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-05T10:57:07.890686+00:00'
[2025-05-05T10:58:33.632+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-05-05T10:58:33.634+0000] {base.py:73} INFO - Using connection ID 'minio_default' for task execution.
[2025-05-05T10:58:33.636+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_default', conn_type='aws') credentials retrieved from login and password.
[2025-05-05T10:58:53.455+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-05T10:58:53.627+0000] {sql.py:418} INFO - Running statement: 
                    INSERT INTO lineups (
                        match_id, team_id, player_id, player_name, player_nickname,
                        jersey_number, country_id, country_name
                    ) VALUES (
                        %(match_id)s, %(team_id)s, %(player_id)s, %(player_name)s,
                        %(player_nickname)s, %(jersey_number)s, %(country_id)s, %(country_name)s
                    )
                    ON CONFLICT (match_id, team_id, player_id) DO NOTHING;
                    , parameters: {'match_id': 3890268, 'team_id': 173, 'player_id': 5569, 'player_name': 'Marvin Plattenhardt', 'player_nickname': None, 'jersey_number': 21, 'country_id': 85, 'country_name': 'Germany'}
[2025-05-05T10:58:53.688+0000] {sql.py:427} INFO - Rows affected: 0
[2025-05-05T10:58:53.694+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-05T10:58:53.766+0000] {sql.py:418} INFO - Running statement: 
                    INSERT INTO lineups (
                        match_id, team_id, player_id, player_name, player_nickname,
                        jersey_number, country_id, country_name
                    ) VALUES (
                        %(match_id)s, %(team_id)s, %(player_id)s, %(player_name)s,
                        %(player_nickname)s, %(jersey_number)s, %(country_id)s, %(country_name)s
                    )
                    ON CONFLICT (match_id, team_id, player_id) DO NOTHING;
                    , parameters: {'match_id': 3890268, 'team_id': 173, 'player_id': 5697, 'player_name': 'Genki Haraguchi', 'player_nickname': None, 'jersey_number': 24, 'country_id': 114, 'country_name': 'Japan'}
[2025-05-05T10:58:53.801+0000] {sql.py:427} INFO - Rows affected: 0
[2025-05-05T10:58:53.814+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-05T10:58:53.923+0000] {sql.py:418} INFO - Running statement: 
                    INSERT INTO lineups (
                        match_id, team_id, player_id, player_name, player_nickname,
                        jersey_number, country_id, country_name
                    ) VALUES (
                        %(match_id)s, %(team_id)s, %(player_id)s, %(player_name)s,
                        %(player_nickname)s, %(jersey_number)s, %(country_id)s, %(country_name)s
                    )
                    ON CONFLICT (match_id, team_id, player_id) DO NOTHING;
                    , parameters: {'match_id': 3890268, 'team_id': 173, 'player_id': 8575, 'player_name': 'Salomon Armand Magloire Kalou', 'player_nickname': 'Salomon Kalou', 'jersey_number': 8, 'country_id': 55, 'country_name': "Côte d'Ivoire"}
[2025-05-05T10:58:54.027+0000] {sql.py:427} INFO - Rows affected: 0
[2025-05-05T10:58:54.109+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-05T10:58:54.276+0000] {sql.py:418} INFO - Running statement: 
                    INSERT INTO lineups (
                        match_id, team_id, player_id, player_name, player_nickname,
                        jersey_number, country_id, country_name
                    ) VALUES (
                        %(match_id)s, %(team_id)s, %(player_id)s, %(player_name)s,
                        %(player_nickname)s, %(jersey_number)s, %(country_id)s, %(country_name)s
                    )
                    ON CONFLICT (match_id, team_id, player_id) DO NOTHING;
                    , parameters: {'match_id': 3890268, 'team_id': 173, 'player_id': 8576, 'player_name': 'Mitchell Weiser', 'player_nickname': None, 'jersey_number': 20, 'country_id': 85, 'country_name': 'Germany'}
[2025-05-05T10:58:54.342+0000] {sql.py:427} INFO - Rows affected: 0
[2025-05-05T10:58:54.447+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-05T10:58:54.741+0000] {sql.py:418} INFO - Running statement: 
                    INSERT INTO lineups (
                        match_id, team_id, player_id, player_name, player_nickname,
                        jersey_number, country_id, country_name
                    ) VALUES (
                        %(match_id)s, %(team_id)s, %(player_id)s, %(player_name)s,
                        %(player_nickname)s, %(jersey_number)s, %(country_id)s, %(country_name)s
                    )
                    ON CONFLICT (match_id, team_id, player_id) DO NOTHING;
                    , parameters: {'match_id': 3890268, 'team_id': 173, 'player_id': 8577, 'player_name': 'Rune Almenning Jarstein', 'player_nickname': 'Rune Jarstein', 'jersey_number': 22, 'country_id': 171, 'country_name': 'Norway'}
[2025-05-05T10:58:54.855+0000] {sql.py:427} INFO - Rows affected: 0
[2025-05-05T10:58:55.087+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-05T10:58:55.541+0000] {sql.py:418} INFO - Running statement: 
                    INSERT INTO lineups (
                        match_id, team_id, player_id, player_name, player_nickname,
                        jersey_number, country_id, country_name
                    ) VALUES (
                        %(match_id)s, %(team_id)s, %(player_id)s, %(player_name)s,
                        %(player_nickname)s, %(jersey_number)s, %(country_id)s, %(country_name)s
                    )
                    ON CONFLICT (match_id, team_id, player_id) DO NOTHING;
                    , parameters: {'match_id': 3890268, 'team_id': 173, 'player_id': 8578, 'player_name': 'Per Ciljan Skjelbred', 'player_nickname': None, 'jersey_number': 3, 'country_id': 171, 'country_name': 'Norway'}
[2025-05-05T10:58:55.665+0000] {sql.py:427} INFO - Rows affected: 0
[2025-05-05T10:58:56.012+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-05T10:58:57.042+0000] {sql.py:418} INFO - Running statement: 
                    INSERT INTO lineups (
                        match_id, team_id, player_id, player_name, player_nickname,
                        jersey_number, country_id, country_name
                    ) VALUES (
                        %(match_id)s, %(team_id)s, %(player_id)s, %(player_name)s,
                        %(player_nickname)s, %(jersey_number)s, %(country_id)s, %(country_name)s
                    )
                    ON CONFLICT (match_id, team_id, player_id) DO NOTHING;
                    , parameters: {'match_id': 3890268, 'team_id': 173, 'player_id': 8579, 'player_name': 'Vladimír Darida', 'player_nickname': None, 'jersey_number': 6, 'country_id': 60, 'country_name': 'Czech Republic'}
[2025-05-05T10:58:57.101+0000] {sql.py:427} INFO - Rows affected: 0
[2025-05-05T10:58:58.085+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-05T10:58:59.254+0000] {sql.py:418} INFO - Running statement: 
                    INSERT INTO lineups (
                        match_id, team_id, player_id, player_name, player_nickname,
                        jersey_number, country_id, country_name
                    ) VALUES (
                        %(match_id)s, %(team_id)s, %(player_id)s, %(player_name)s,
                        %(player_nickname)s, %(jersey_number)s, %(country_id)s, %(country_name)s
                    )
                    ON CONFLICT (match_id, team_id, player_id) DO NOTHING;
                    , parameters: {'match_id': 3890268, 'team_id': 173, 'player_id': 8580, 'player_name': 'Sebastian Langkamp', 'player_nickname': None, 'jersey_number': 15, 'country_id': 85, 'country_name': 'Germany'}
[2025-05-05T10:58:59.564+0000] {sql.py:427} INFO - Rows affected: 0
[2025-05-05T10:58:59.772+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-05T10:59:00.923+0000] {sql.py:418} INFO - Running statement: 
                    INSERT INTO lineups (
                        match_id, team_id, player_id, player_name, player_nickname,
                        jersey_number, country_id, country_name
                    ) VALUES (
                        %(match_id)s, %(team_id)s, %(player_id)s, %(player_name)s,
                        %(player_nickname)s, %(jersey_number)s, %(country_id)s, %(country_name)s
                    )
                    ON CONFLICT (match_id, team_id, player_id) DO NOTHING;
                    , parameters: {'match_id': 3890268, 'team_id': 173, 'player_id': 8883, 'player_name': 'Johannes van den Bergh', 'player_nickname': None, 'jersey_number': 23, 'country_id': 85, 'country_name': 'Germany'}
[2025-05-05T10:59:01.691+0000] {sql.py:427} INFO - Rows affected: 0
[2025-05-05T10:59:02.008+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-05T10:59:02.387+0000] {sql.py:418} INFO - Running statement: 
                    INSERT INTO lineups (
                        match_id, team_id, player_id, player_name, player_nickname,
                        jersey_number, country_id, country_name
                    ) VALUES (
                        %(match_id)s, %(team_id)s, %(player_id)s, %(player_name)s,
                        %(player_nickname)s, %(jersey_number)s, %(country_id)s, %(country_name)s
                    )
                    ON CONFLICT (match_id, team_id, player_id) DO NOTHING;
                    , parameters: {'match_id': 3890268, 'team_id': 173, 'player_id': 8965, 'player_name': 'Fabian Lustenberger', 'player_nickname': None, 'jersey_number': 28, 'country_id': 221, 'country_name': 'Switzerland'}
[2025-05-05T10:59:03.516+0000] {sql.py:427} INFO - Rows affected: 0
[2025-05-05T10:59:04.358+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-05T10:59:07.044+0000] {sql.py:418} INFO - Running statement: 
                    INSERT INTO lineups (
                        match_id, team_id, player_id, player_name, player_nickname,
                        jersey_number, country_id, country_name
                    ) VALUES (
                        %(match_id)s, %(team_id)s, %(player_id)s, %(player_name)s,
                        %(player_nickname)s, %(jersey_number)s, %(country_id)s, %(country_name)s
                    )
                    ON CONFLICT (match_id, team_id, player_id) DO NOTHING;
                    , parameters: {'match_id': 3890268, 'team_id': 173, 'player_id': 9721, 'player_name': 'Valentin Stocker', 'player_nickname': None, 'jersey_number': 14, 'country_id': 221, 'country_name': 'Switzerland'}
[2025-05-05T10:59:08.284+0000] {sql.py:427} INFO - Rows affected: 0
[2025-05-05T10:59:09.019+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-05T10:59:11.485+0000] {sql.py:418} INFO - Running statement: 
                    INSERT INTO lineups (
                        match_id, team_id, player_id, player_name, player_nickname,
                        jersey_number, country_id, country_name
                    ) VALUES (
                        %(match_id)s, %(team_id)s, %(player_id)s, %(player_name)s,
                        %(player_nickname)s, %(jersey_number)s, %(country_id)s, %(country_name)s
                    )
                    ON CONFLICT (match_id, team_id, player_id) DO NOTHING;
                    , parameters: {'match_id': 3890268, 'team_id': 173, 'player_id': 9722, 'player_name': 'Peter Pekarík', 'player_nickname': None, 'jersey_number': 2, 'country_id': 207, 'country_name': 'Slovakia'}
[2025-05-05T10:59:11.527+0000] {sql.py:427} INFO - Rows affected: 0
[2025-05-05T10:59:11.531+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-05T10:59:11.753+0000] {sql.py:418} INFO - Running statement: 
                    INSERT INTO lineups (
                        match_id, team_id, player_id, player_name, player_nickname,
                        jersey_number, country_id, country_name
                    ) VALUES (
                        %(match_id)s, %(team_id)s, %(player_id)s, %(player_name)s,
                        %(player_nickname)s, %(jersey_number)s, %(country_id)s, %(country_name)s
                    )
                    ON CONFLICT (match_id, team_id, player_id) DO NOTHING;
                    , parameters: {'match_id': 3890268, 'team_id': 173, 'player_id': 12327, 'player_name': 'John Anthony Brooks', 'player_nickname': 'John Brooks', 'jersey_number': 25, 'country_id': 241, 'country_name': 'United States of America'}
[2025-05-05T10:59:12.450+0000] {sql.py:427} INFO - Rows affected: 0
[2025-05-05T10:59:12.770+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-05T10:59:15.606+0000] {sql.py:418} INFO - Running statement: 
                    INSERT INTO lineups (
                        match_id, team_id, player_id, player_name, player_nickname,
                        jersey_number, country_id, country_name
                    ) VALUES (
                        %(match_id)s, %(team_id)s, %(player_id)s, %(player_name)s,
                        %(player_nickname)s, %(jersey_number)s, %(country_id)s, %(country_name)s
                    )
                    ON CONFLICT (match_id, team_id, player_id) DO NOTHING;
                    , parameters: {'match_id': 3890268, 'team_id': 173, 'player_id': 12407, 'player_name': 'Maximilian Mittelstädt', 'player_nickname': None, 'jersey_number': 34, 'country_id': 85, 'country_name': 'Germany'}
[2025-05-05T10:59:19.204+0000] {sql.py:427} INFO - Rows affected: 0
[2025-05-05T10:59:20.577+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-05T10:59:24.322+0000] {sql.py:418} INFO - Running statement: 
                    INSERT INTO lineups (
                        match_id, team_id, player_id, player_name, player_nickname,
                        jersey_number, country_id, country_name
                    ) VALUES (
                        %(match_id)s, %(team_id)s, %(player_id)s, %(player_name)s,
                        %(player_nickname)s, %(jersey_number)s, %(country_id)s, %(country_name)s
                    )
                    ON CONFLICT (match_id, team_id, player_id) DO NOTHING;
                    , parameters: {'match_id': 3890268, 'team_id': 173, 'player_id': 17313, 'player_name': 'Thomas Kraft', 'player_nickname': None, 'jersey_number': 1, 'country_id': 85, 'country_name': 'Germany'}
[2025-05-05T10:59:25.970+0000] {sql.py:427} INFO - Rows affected: 0
[2025-05-05T10:59:26.262+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-05T10:59:29.021+0000] {sql.py:418} INFO - Running statement: 
                    INSERT INTO lineups (
                        match_id, team_id, player_id, player_name, player_nickname,
                        jersey_number, country_id, country_name
                    ) VALUES (
                        %(match_id)s, %(team_id)s, %(player_id)s, %(player_name)s,
                        %(player_nickname)s, %(jersey_number)s, %(country_id)s, %(country_name)s
                    )
                    ON CONFLICT (match_id, team_id, player_id) DO NOTHING;
                    , parameters: {'match_id': 3890268, 'team_id': 173, 'player_id': 33459, 'player_name': 'Alexander Baumjohann', 'player_nickname': None, 'jersey_number': 9, 'country_id': 85, 'country_name': 'Germany'}
[2025-05-05T10:59:33.005+0000] {sql.py:427} INFO - Rows affected: 0
[2025-05-05T10:59:36.060+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-05T10:59:56.245+0000] {sql.py:418} INFO - Running statement: 
                    INSERT INTO lineups (
                        match_id, team_id, player_id, player_name, player_nickname,
                        jersey_number, country_id, country_name
                    ) VALUES (
                        %(match_id)s, %(team_id)s, %(player_id)s, %(player_name)s,
                        %(player_nickname)s, %(jersey_number)s, %(country_id)s, %(country_name)s
                    )
                    ON CONFLICT (match_id, team_id, player_id) DO NOTHING;
                    , parameters: {'match_id': 3890268, 'team_id': 173, 'player_id': 40474, 'player_name': 'Jens Hegeler', 'player_nickname': None, 'jersey_number': 13, 'country_id': 85, 'country_name': 'Germany'}
[2025-05-05T11:00:03.512+0000] {sql.py:427} INFO - Rows affected: 0
[2025-05-05T11:00:19.579+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-05T11:20:16.755+0000] {local_task_job_runner.py:205} ERROR - Heartbeat time limit exceeded!
[2025-05-05T11:20:16.936+0000] {process_utils.py:131} INFO - Sending 15 to group 267. PIDs of all processes in the group: [267]
[2025-05-05T11:20:16.938+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 267
[2025-05-05T11:20:17.011+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-05T11:20:17.048+0000] {logging_mixin.py:151} WARNING - --- Logging error ---
[2025-05-05T11:20:17.134+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2025-05-05T11:20:17.138+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2025-05-05T11:20:17.140+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2025-05-05T11:20:17.142+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2025-05-05T11:20:17.146+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2025-05-05T11:20:17.147+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2025-05-05T11:20:17.150+0000] {logging_mixin.py:151} WARNING -   File "/opt/airflow/dags/load_to_postgres.py", line 148, in load_lineups
    hook_pg.run(
[2025-05-05T11:20:17.152+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
[2025-05-05T11:20:17.153+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 154, in get_conn
    self.conn = psycopg2.connect(**conn_args)
[2025-05-05T11:20:17.154+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
[2025-05-05T11:20:17.155+0000] {logging_mixin.py:151} WARNING - psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution
[2025-05-05T11:20:17.164+0000] {logging_mixin.py:151} WARNING - 
During handling of the above exception, another exception occurred:
[2025-05-05T11:20:17.166+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2025-05-05T11:20:17.168+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
[2025-05-05T11:20:17.170+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
[2025-05-05T11:20:17.172+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 676, in format
    record.exc_text = self.formatException(record.exc_info)
[2025-05-05T11:20:17.174+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 626, in formatException
    traceback.print_exception(ei[0], ei[1], tb, None, sio)
[2025-05-05T11:20:17.175+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/traceback.py", line 103, in print_exception
    for line in TracebackException(
[2025-05-05T11:20:17.176+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/exceptiongroup/_formatting.py", line 96, in __init__
    self.stack = traceback.StackSummary.extract(
[2025-05-05T11:20:17.178+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/traceback.py", line 362, in extract
    linecache.checkcache(filename)
[2025-05-05T11:20:17.179+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/linecache.py", line 74, in checkcache
    stat = os.stat(fullname)
[2025-05-05T11:20:17.181+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1632, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
[2025-05-05T11:20:17.183+0000] {logging_mixin.py:151} WARNING - airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-05-05T11:20:17.185+0000] {logging_mixin.py:151} WARNING - Call stack:
[2025-05-05T11:20:17.217+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
[2025-05-05T11:20:17.220+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/__main__.py", line 59, in main
    args.func(args)
[2025-05-05T11:20:17.223+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2025-05-05T11:20:17.225+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2025-05-05T11:20:17.227+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2025-05-05T11:20:17.228+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/scheduler_command.py", line 85, in scheduler
    _run_scheduler_job(job_runner, skip_serve_logs=args.skip_serve_logs)
[2025-05-05T11:20:17.231+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/scheduler_command.py", line 47, in _run_scheduler_job
    run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2025-05-05T11:20:17.233+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2025-05-05T11:20:17.235+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2025-05-05T11:20:17.236+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2025-05-05T11:20:17.238+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/scheduler_job_runner.py", line 836, in _execute
    self.job.executor.start()
[2025-05-05T11:20:17.241+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/executors/local_executor.py", line 371, in start
    self.impl.start()
[2025-05-05T11:20:17.243+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/executors/local_executor.py", line 308, in start
    worker.start()
[2025-05-05T11:20:17.244+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
[2025-05-05T11:20:17.245+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
[2025-05-05T11:20:17.248+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
[2025-05-05T11:20:17.250+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
[2025-05-05T11:20:17.251+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/multiprocessing/popen_fork.py", line 75, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
[2025-05-05T11:20:17.252+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
[2025-05-05T11:20:17.254+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/executors/local_executor.py", line 74, in run
    return super().run()
[2025-05-05T11:20:17.255+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
[2025-05-05T11:20:17.257+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/executors/local_executor.py", line 198, in do_work
    self.execute_work(key=key, command=command)
[2025-05-05T11:20:17.281+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/executors/local_executor.py", line 91, in execute_work
    state = self._execute_work_in_fork(command)
[2025-05-05T11:20:17.283+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/executors/local_executor.py", line 131, in _execute_work_in_fork
    args.func(args)
[2025-05-05T11:20:17.284+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2025-05-05T11:20:17.286+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2025-05-05T11:20:17.287+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2025-05-05T11:20:17.289+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2025-05-05T11:20:17.289+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2025-05-05T11:20:17.291+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2025-05-05T11:20:17.292+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2025-05-05T11:20:17.294+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2025-05-05T11:20:17.296+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2025-05-05T11:20:17.297+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2025-05-05T11:20:17.299+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2025-05-05T11:20:17.300+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2025-05-05T11:20:17.302+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2025-05-05T11:20:17.303+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2025-05-05T11:20:17.304+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2025-05-05T11:20:17.305+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2025-05-05T11:20:17.307+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2025-05-05T11:20:17.308+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1570, in _run_raw_task
    self.handle_failure(e, test_mode, context, session=session)
[2025-05-05T11:20:17.310+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
[2025-05-05T11:20:17.311+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1935, in handle_failure
    self.log.error("Task failed with exception", exc_info=(type(error), error, tb))
[2025-05-05T11:20:17.312+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
[2025-05-05T11:20:17.313+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
[2025-05-05T11:20:17.315+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
[2025-05-05T11:20:17.316+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
[2025-05-05T11:20:17.318+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 954, in handle
    self.emit(record)
[2025-05-05T11:20:17.319+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_task_handler.py", line 211, in emit
    self.handler.emit(record)
[2025-05-05T11:20:17.320+0000] {logging_mixin.py:151} WARNING - Message: 'Task failed with exception'
Arguments: ()
[2025-05-05T11:20:17.478+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=statsbomb_load_postgres, task_id=load_lineups, execution_date=20250505T105707, start_date=20250505T105833, end_date=20250505T112017
[2025-05-05T11:20:17.620+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 85 for task load_lineups (could not translate host name "postgres" to address: Temporary failure in name resolution
; 267)
[2025-05-05T11:20:17.649+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=267, status='terminated', exitcode=1, started='10:58:32') (267) terminated with exit code 1
